language: python
python:
  - "3.7"

install:
  - pip install .
  - python -c "from mo_sql_parsing import parse; print(parse(\"select count(1) from jobs\"))"
  - pip install -r tests/requirements.txt

env:
  - PYTHONPATH=.

# command to run tests
script:
  - python -m unittest discover tests
