language: python
python:
  - "2.7"
  - "3.7"

install:
  - pip install -r tests/requirements.txt
  - pip install .

env:
  - PYTHONPATH=.

# command to run tests
script:
  - python -m unittest discover tests
